config/routes.rb
Rails.application.routes.draw do
  resources :monster_templates
  root to: 'application#index'
  resources :adventurers, only: [:create]
  resources :events, only: [:create]
  resources :facilities, only: [:create]
  resources :guild, only: [:create]
  resources :guildmaster, only: [:create]
  resources :quests, only: [:create]
  resources :accounts, only: [:create]
  resources :guild_sessions, only: [:create]
  delete 'sessions' => 'sessions#destroy'
  resources :sessions, only: [:create, :delete]

  namespace :admin do
    root to: 'dashboard#new'
    resources :adventurer_names
    resources :adventurer_templates
    resources :monster_templates
    resources :accounts
    resources :quest_descriptions
    resources :dashboard
  end
  get '*any', via: :all, to: 'errors#not_found'
  # get "*path", to: redirect('/')
end

app/models/quest_description.rb
class QuestDescription < ActiveRecord::Base
end

app/controllers/admin/quest_descriptions_controller.rb
class Admin::QuestDescriptionsController < AdminController
  before_action :set_quest_description, only: [:show, :edit, :update, :destroy]
  before_action :authorized_admin

  def index
    @grid = QuestDescriptionsGrid.new(params[:quest_descriptions_grid]) do |scope|
      scope.page(params[:page])
    end
  end

  def show
  end

  def new
    @quest_description = QuestDescription.new
  end

  def create
    @quest_description = QuestDescription.new(quest_description_params)

    respond_to do |format|
      if @quest_description.save
        format.html { redirect_to [:admin, @quest_description], notice: 'Quest description was successfully created.' }
        format.json { render :show, status: :created, location: @quest_description }
      else
        format.html { render :new }
        format.json { render json: @quest_description.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @quest_description.update(quest_description_params)
        format.html { redirect_to [:admin, @quest_description], notice: 'Quest description was successfully updated.' }
        format.json { render :show, status: :ok, location: @quest_description }
      else
        format.html { render :edit }
        format.json { render json: @quest_description.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @quest_description.destroy
    respond_to do |format|
      format.html { redirect_to admin_quest_descriptions_path, notice: 'Quest description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_quest_description
    @quest_description = QuestDescription.find(params[:id])
  end

  def quest_description_params
    params.require(:quest_description).permit(:description)
  end
end

app/views/admin/quest_descriptions/_form.html.erb
<%= form_for [:admin, @quest_description] do |f| %>
  <% if @quest_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quest_description.errors.count, "error") %> prohibited this quest description from being saved:</h2>

      <ul>
      <% @quest_description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/quest_descriptions/edit.html.erb
<h1>Editing Quest Description</h1>
<p><%= link_to 'Logout', admin_root_path %></p>
<%= render 'form' %>

<%= link_to 'Back', admin_quest_descriptions_path %>

app/views/admin/quest_descriptions/index.html.erb
<h1>Listing Quest Description</h1>

<p><%= link_to 'Logout', admin_root_path %></p>
<p><%= link_to 'Back to Dashboard', :controller => 'admin/dashboard', :action => 'index' %></p>
<p><%= link_to "New Quest Description", new_admin_quest_description_path %></p><br>


<%= datagrid_form_for @grid, :method => :get, :url => admin_quest_descriptions_path %>

<%= paginate(@grid.assets) %>
<%#	assets = @grid.assets.page(params[:page]) %>
<%= datagrid_table(@grid, :html => {:class => "table table-hover"}) %>
<%= paginate(@grid.assets) %>

app/views/admin/quest_descriptions/new.html.erb
<h1>New Quest Description</h1>
<p><%= link_to 'Logout', admin_root_path %></p>
<%= render 'form' %>

<%= link_to 'Back', admin_quest_descriptions_path %>

app/views/admin/quest_descriptions/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= link_to 'Logout', admin_root_path %></p>
<p>
  <strong>Description:</strong>
  <%= @quest_description.description %>
</p>

<%= link_to 'Edit', edit_admin_quest_description_path(@quest_description) %> |
<%= link_to 'Back', admin_quest_descriptions_path %>