config/routes.rb
Rails.application.routes.draw do
  resources :monster_templates
  root to: 'application#index'
  resources :adventurers, only: [:create]
  resources :events, only: [:create]
  resources :facilities, only: [:create]
  resources :guild, only: [:create]
  resources :guildmaster, only: [:create]
  resources :quests, only: [:create]
  resources :accounts, only: [:create]
  resources :guild_sessions, only: [:create]
  delete 'sessions' => 'sessions#destroy'
  resources :sessions, only: [:create, :delete]

  namespace :admin do
    root to: 'dashboard#new'
    resources :adventurer_names
    resources :adventurer_templates
    resources :monster_templates
    resources :accounts
    resources :quest_descriptions
    resources :dashboard
  end
  get '*any', via: :all, to: 'errors#not_found'
  # get "*path", to: redirect('/')
end

app/models/adventurer_template.rb
class AdventurerTemplate < ActiveRecord::Base
  belongs_to :region
end

app/controllers/admin/adventurer_templates_controller.rb
class Admin::AdventurerTemplatesController < AdminController
  before_action :set_adventurer_template, only: [:show, :edit, :update, :destroy]
  before_action :authorized_admin

  def index
    @grid = AdventurerTemplatesGrid.new(params[:adventurer_templates_grid]) do |scope|
      scope.page(params[:page])
    end
  end

  def show
  end

  def new
    @adventurer_template = AdventurerTemplate.new
  end

  def create
    @adventurer_template = AdventurerTemplate.new(adventurer_template_params)

    respond_to do |format|
      if @adventurer_template.save
        format.html { redirect_to [:admin, @adventurer_template], notice: 'Adventurer template was successfully created.' }
        format.json { render :show, status: :created, location: @adventurer_template }
      else
        format.html { render :new }
        format.json { render json: @adventurer_template.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @adventurer_template.update(adventurer_template_params)
        format.html { redirect_to [:admin, @adventurer_template], notice: 'Adventurer template was successfully updated.' }
        format.json { render :show, status: :ok, location: @adventurer_template }
      else
        format.html { render :edit }
        format.json { render json: @adventurer_template.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @adventurer_template.destroy
    respond_to do |format|
      format.html { redirect_to admin_adventurer_templates_path, notice: 'Adventurer template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_adventurer_template
    @adventurer_template = AdventurerTemplate.find(params[:id])
  end

  def adventurer_template_params
    params.require(:adventurer_template).permit(:max_hp, :max_energy, :attack, :defense, :vision)
  end
end

app/views/admin/adventurer_templates/_form.html.erb
<%= form_for [:admin, @adventurer_template] do |f| %>
  <% if @adventurer_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventurer_template.errors.count, "error") %> prohibited this adventurer_template from being saved:</h2>

      <ul>
      <% @adventurer_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :max_hp %><br>
    <%= f.number_field :max_hp %>
  </div>
  <div class="field">
    <%= f.label :max_energy %><br>
    <%= f.number_field :max_energy %>
  </div>
  <div class="field">
    <%= f.label :attack %><br>
    <%= f.number_field :attack %>
  </div>
  <div class="field">
    <%= f.label :defense %><br>
    <%= f.number_field :defense %>
  </div>
  <div class="field">
    <%= f.label :vision %><br>
    <%= f.number_field :vision %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/adventurer_templates/edit.html.erb
<h1>Editing Adventurer Template</h1>
<p><%= link_to 'Logout', admin_root_path %></p>
<%= render 'form' %>

<%= link_to 'Back', admin_adventurer_templates_path %>

app/views/admin/adventurer_templates/index.html.erb
<h1>Listing Adventurer Template</h1>

<p><%= link_to 'Logout', admin_root_path %></p>
<p><%= link_to 'Back to Dashboard', :controller => 'admin/dashboard', :action => 'index' %></p>
<p><%= link_to "New Adventurer Template", new_admin_adventurer_template_path %></p><br>


<%= datagrid_form_for @grid, :method => :get, :url => admin_adventurer_templates_path %>

<%= paginate(@grid.assets) %>
<%#	assets = @grid.assets.page(params[:page]) %>
<%= datagrid_table(@grid, :html => {:class => "table table-hover"}) %>
<%= paginate(@grid.assets) %>

app/views/admin/adventurer_templates/new.html.erb
<h1>New Adventurer Template</h1>
<p><%= link_to 'Logout', admin_root_path %></p>
<%= render 'form' %>

<%= link_to 'Back', admin_adventurer_templates_path %>

app/views/admin/adventurer_templates/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= link_to 'Logout', admin_root_path %></p>

<p>
  <strong>Max HP:</strong>
  <%= @adventurer_template.max_hp %>
</p>
<p>
  <strong>Max Energy:</strong>
  <%= @adventurer_template.max_energy %>
</p>
<p>
  <strong>Attack:</strong>
  <%= @adventurer_template.attack %>
</p>
<p>
  <strong>Defense:</strong>
  <%= @adventurer_template.defense %>
</p>
<p>
  <strong>Vision:</strong>
  <%= @adventurer_template.vision %>
</p>
<%= link_to 'Edit', edit_admin_adventurer_template_path(@adventurer_template) %> |
<%= link_to 'Back', admin_adventurer_templates_path %>