config/routes.rb
Rails.application.routes.draw do
  resources :monster_templates
  root to: 'application#index'
  resources :adventurers, only: [:create]
  resources :events, only: [:create]
  resources :facilities, only: [:create]
  resources :guild, only: [:create]
  resources :guildmaster, only: [:create]
  resources :quests, only: [:create]
  resources :accounts, only: [:create]
  resources :guild_sessions, only: [:create]
  delete 'sessions' => 'sessions#destroy'
  resources :sessions, only: [:create, :delete]

  namespace :admin do
    root to: 'dashboard#new'
    resources :adventurer_names
    resources :adventurer_templates
    resources :monster_templates
    resources :accounts
    resources :quest_descriptions
    resources :dashboard
  end
  get '*any', via: :all, to: 'errors#not_found'
  # get "*path", to: redirect('/')
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  before_action :authorized_admin, except: [:new]
  def index
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Admin Dashboard</h1>
<p><%= link_to 'Logout', admin_root_path %></p>
<p><%= link_to 'Manage Adventurer Names', admin_adventurer_names_path %></p>
<p><%= link_to 'Manage Adventurer Templates', admin_adventurer_templates_path %></p>
<p><%= link_to 'Manage Monster Templates', admin_monster_templates_path %></p>
<p><%= link_to 'Manage Accounts', admin_accounts_path %></p>
<p><%= link_to 'Manage Quest Descriptions', admin_quest_descriptions_path %></p>

app/views/admin/dashboard/new.html.erb
<div class="container-fluid">
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">

    <h1>Admin Dashboard - Sign in page</h1>

    <%= form_tag('/sessions') do %>
      <%= hidden_field_tag :is_admin_page, true %>
      <div class="form-group">
        <%= label_tag :email %>
        <%= text_field_tag :email, nil, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :password %>
        <%= password_field_tag :password, nil, class: "form-control" %>
      </div>
      <%= submit_tag "Sign in", class: "btn btn-primary" %>
      <% session.delete(:admin_id) %>
    <% end %>
  </div>
</div>