config/routes.rb
Rails.application.routes.draw do
  resources :monster_templates
  root to: 'application#index'
  resources :adventurers, only: [:create]
  resources :events, only: [:create]
  resources :facilities, only: [:create]
  resources :guild, only: [:create]
  resources :guildmaster, only: [:create]
  resources :quests, only: [:create]
  resources :accounts, only: [:create]
  resources :guild_sessions, only: [:create]
  delete 'sessions' => 'sessions#destroy'
  resources :sessions, only: [:create, :delete]

  namespace :admin do
    root to: 'dashboard#new'
    resources :adventurer_names
    resources :adventurer_templates
    resources :monster_templates
    resources :accounts
    resources :quest_descriptions
    resources :dashboard
  end
  get '*any', via: :all, to: 'errors#not_found'
  # get "*path", to: redirect('/')
end

app/models/adventurer_name.rb
class AdventurerName < ActiveRecord::Base
end

app/controllers/admin/adventurer_names_controller.rb
class Admin::AdventurerNamesController < AdminController
  before_action :set_adventurer_name, only: [:show, :edit, :update, :destroy]
  before_action :authorized_admin

  def index
    @grid = AdventurerNamesGrid.new(params[:adventurer_names_grid]) do |scope|
      scope.page(params[:page])
    end
  end

  def show
  end

  def new
    @adventurer_name = AdventurerName.new
  end

  def edit
  end

  def create
    @adventurer_name = AdventurerName.new(adventurer_name_params)

    respond_to do |format|
      if @adventurer_name.save
        format.html { redirect_to [:admin, @adventurer_name], notice: 'Adventurer name was successfully created.' }
        format.json { render :show, status: :created, location: @adventurer_name }
      else
        format.html { render :new }
        format.json { render json: @adventurer_name.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @adventurer_name.update(adventurer_name_params)
        format.html { redirect_to [:admin, @adventurer_name], notice: 'Adventurer name was successfully updated.' }
        format.json { render :show, status: :ok, location: @adventurer_name }
      else
        format.html { render :edit }
        format.json { render json: @adventurer_name.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @adventurer_name.destroy
    respond_to do |format|
      format.html { redirect_to admin_adventurer_names_path, notice: 'Adventurer name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_adventurer_name
    @adventurer_name = AdventurerName.find(params[:id])
  end

  def adventurer_name_params
    params.require(:adventurer_name).permit(:name)
  end
end

app/helpers/adventurer_names_helper.rb
module AdventurerNamesHelper
end

app/views/admin/adventurer_names/_form.html.erb
<%= form_for [:admin, @adventurer_name] do |f| %>
  <% if @adventurer_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventurer_name.errors.count, "error") %> prohibited this adventurer_name from being saved:</h2>

      <ul>
      <% @adventurer_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/adventurer_names/edit.html.erb
<h1>Editing Adventurer Name</h1>
<p><%= link_to 'Logout', admin_root_path %></p>
<%= render 'form' %>

<%= link_to 'Back', admin_adventurer_names_path %>

app/views/admin/adventurer_names/index.html.erb
<h1>Listing Adventurer Name</h1>

<p><%= link_to 'Logout', admin_root_path %></p>
<p><%= link_to 'Back to Dashboard', :controller => 'admin/dashboard', :action => 'index' %></p>
<p><%= link_to "New Adventurer Name", new_admin_adventurer_name_path %></p><br>


<%= datagrid_form_for @grid, :method => :get, :url => admin_adventurer_names_path %>

<%= paginate(@grid.assets) %>
<%# assets = @grid.assets.page(params[:page]) %>
<%= datagrid_table(@grid, :html => {:class => "table table-hover"}) %>
<%= paginate(@grid.assets) %>

app/views/admin/adventurer_names/new.html.erb
<h1>New Adventurer Name</h1>
<p><%= link_to 'Logout', admin_root_path %></p>
<%= render 'form' %>

<%= link_to 'Back', admin_adventurer_names_path %>

app/views/admin/adventurer_names/show.html.erb
<p id="notice"><%= notice %></p>
<p><%= link_to 'Logout', admin_root_path %></p>
<p>
  <strong>Name:</strong>
  <%= @adventurer_name.name %>
</p>

<%= link_to 'Edit', edit_admin_adventurer_name_path(@adventurer_name) %> |
<%= link_to 'Back', admin_adventurer_names_path %>